#! /bin/sh

sxhkd & $HOME/.config/polybar/launch.sh & picom & $HOME/wallpaper.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          20
bspc config bottom_padding      35
bspc config top_padding          0

bspc config normal_border_color #3399FF
bspc config active_border_color #3399FF
bspc config focused_border_color #3399FF

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
